# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - red-privateapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_MI_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.AZURE_ACR_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.linux
          push: true
          tags: ${{ vars.AZURE_ACR_NAME }}.azurecr.io/dotnetcore-docs-hello-world:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_MI_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Set app settings
        run: |
          az webapp config appsettings set \
            --resource-group "${{ vars.AZURE_RG_NAME }}" \
            --name "${{ vars.AZURE_APP_NAME }}" \
            --settings EMBED_ALLOWED_ORIGINS="https://teams.microsoft.com,https://localhost:53000"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          images: ${{ vars.AZURE_ACR_NAME }}.azurecr.io/dotnetcore-docs-hello-world:latest

      - name: Ensure app is using mi to connect to ACR
        run: |
          az webapp config set --name ${{ vars.AZURE_APP_NAME }} --resource-group ${{ vars.AZURE_RG_NAME }} --generic-configurations '{"acrUseManagedIdentityCreds":true,"acrUserManagedIdentityID":"${{ secrets.AZURE_MI_CLIENT_ID }}"}'

      - name: Sign out of Azure
        run: |
          az logout